import type { CityIconName } from './components/desktop/cityIcons';

/*
 * robOS content file.
 * Everything on the desktop comes from this one file. To add something,
 * copy an item inside a folder's `items` list and change the words.
 *
 * Item types:
 *   note    { type, id, title, date?, body }                           -> opens in Notepad
 *   recipe  { type, id, title, date?, serves?, time?, ingredients, steps, note?, source? }
 *   link    { type, id, title, date?, url, note? }                     -> little browser window with a "Visit" button
 *   video   { type, id, title, date?, url, note? }                     -> media player. YouTube video links
 *                                                                        play right in the window; anything else links out
 *   list    { type, id, title, date?, rows: [{ name, detail, url? }] } -> a table (books, playlists, etc.)
 *   image   { type, id, title, date?, src, thumb?, caption? }          -> photo viewer (src = a file in /public, e.g. "/photos/tourmalet.jpg").
 *                                                                        Shows as a little thumbnail in its folder (`thumb` = a smaller copy)
 *   map     { type, id, title, date?, url?, area?, note?, places?: [{ name, note?, query? }] }
 *                                                                     -> Google Map in a window. `url` is any Google Maps link,
 *                                                                        e.g. your saved list's Share link. `places` shows a
 *                                                                        clickable list; clicking one moves the map to it
 *                                                                        (`query` if the name alone finds the wrong spot).
 *                                                                        `area` is what the map shows before a place is picked
 *   folder  { type, id, title, blurb?, items: [...] }                 -> a folder inside a folder, with its own items
 *
 * Any item can also have `icon: 'paris'` etc. to swap its icon (see IconName below).
 *
 * `id` makes a deep link: robkilometers.ca/#food.lemon-pasta opens that item directly,
 * robkilometers.ca/#food.city-guides.paris works the same way inside a folder in a folder,
 * robkilometers.ca/#food opens the folder, robkilometers.ca/#about opens the profile.
 * Items marked "(sample ...)" are placeholders to show the layout. Replace them with your own.
 */

export type IconName =
  | 'folder'
  | 'trash'
  | 'computer'
  | 'notepad'
  | 'recipe'
  | 'globe'
  | 'film'
  | 'book'
  | 'image'
  | 'mail'
  | 'camera'
  | 'music'
  | 'km'
  | 'shutdown'
  | 'runner'
  | 'tools'
  | 'map'
  | CityIconName;

// `icon` is optional on every item and replaces the default icon for its type.
type ItemBase = { id: string; title: string; date?: string; icon?: IconName };

export type NoteItem = ItemBase & { type: 'note'; body: string };
export type RecipeItem = ItemBase & {
  type: 'recipe';
  serves?: string;
  time?: string;
  ingredients: string[];
  steps: string[];
  note?: string;
  source?: string;
};
export type LinkItem = ItemBase & { type: 'link'; url: string; note?: string };
export type VideoItem = ItemBase & { type: 'video'; url: string; note?: string };
export type ListItem = ItemBase & { type: 'list'; rows: { name: string; detail: string; url?: string }[] };
export type ImageItem = ItemBase & { type: 'image'; src: string; thumb?: string; caption?: string };
export type MapItem = ItemBase & {
  type: 'map';
  url?: string;
  area?: string;
  note?: string;
  places?: { name: string; note?: string; query?: string }[];
};

export type FolderItem = ItemBase & { type: 'folder'; blurb?: string; items: Item[] };

export type ContentItem = NoteItem | RecipeItem | LinkItem | VideoItem | ListItem | ImageItem | MapItem;
export type Item = ContentItem | FolderItem;
export type ItemType = Item['type'];

export type Folder = {
  id: string;
  name: string;
  icon?: IconName;
  blurb?: string;
  items: Item[];
};

export type QuickLink =
  | { label: string; icon: IconName; email: string }
  | { label: string; icon: IconName; url: string };

export type Site = {
  owner: string;
  handle: string;
  location: string;
  coords: string;
  email: string;
  tagline: string;
  taskbar: QuickLink[];
  readme: { title: string; body: string };
  folders: Folder[];
};

export const site: Site = {
  owner: 'Rob Kilometers',
  handle: 'robkilometers',
  location: 'Toronto, ON',
  coords: '43.65°N 79.38°W',
  email: 'hello@robkilometers.ca',
  tagline: "Food, clothes, books, sport and whatever else I'm into this week.",

  // Quick-launch icons on the taskbar. Swap in your real handles.
  taskbar: [
    { label: 'Email me', icon: 'mail', email: 'hello@robkilometers.ca' },
    { label: 'Instagram (add your handle)', icon: 'camera', url: 'https://www.instagram.com/' },
    { label: 'YouTube (add your channel)', icon: 'film', url: 'https://www.youtube.com/' },
    { label: 'Spotify (add a playlist)', icon: 'music', url: 'https://open.spotify.com/' },
  ],

  // Opens automatically on desktop the first time someone visits.
  readme: {
    title: 'README.TXT',
    body: `Welcome to robOS 98.

This is my corner of the internet. It's not a portfolio.
It's food I'm cooking, clothes I like, books I'm reading,
sport I'm watching and whatever I'm thinking about.

Double-click a folder to poke around.
On a phone, just tap.

Start menu, bottom left, has everything in one list.

Last updated: Sept 2026
(sample text, edit me in content.ts)`,
  },

  folders: [
    {
      id: 'food',
      name: 'Food',
      blurb: 'Recipes I actually make, and places and people I learn from.',
      items: [
        {
          type: 'folder',
          id: 'city-guides',
          title: 'City Guides',
          blurb: 'Where I eat and drink when I travel. Straight from my Google Maps lists.',
          items: [
            {
              type: 'map',
              id: 'toronto',
              title: 'Toronto',
              icon: 'toronto',
              area: 'Toronto, Canada',
              note: 'Sample map. Click a place to move the pin. Swap `url` for your own saved list\'s Share link.',
              places: [
                { name: 'St. Lawrence Market', note: 'Peameal bacon sandwich', query: 'St. Lawrence Market, Toronto' },
                { name: 'Kensington Market', note: 'Wander and snack', query: 'Kensington Market, Toronto' },
                { name: 'Pai', note: 'Northern Thai', query: 'Pai Northern Thai Kitchen, Toronto' },
              ],
            },
            {
              type: 'map',
              id: 'paris',
              title: 'Paris',
              icon: 'paris',
              area: 'Paris, France',
              url: 'https://maps.app.goo.gl/y4uj282fdnxmAaPx7',
              note: 'My Paris list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Bistrot des Tournelles', note: 'French', query: 'Bistrot des Tournelles, Paris' },
                { name: 'YARD, Restaurant & Cave à vin nature', note: 'Restaurant', query: 'YARD, Restaurant & Cave à vin nature, Paris' },
                { name: 'ORSO', note: 'Restaurant', query: 'ORSO, Paris' },
                { name: 'Le Servan', note: 'Bistro', query: 'Le Servan, Paris' },
                { name: 'Red Sauce', note: 'Italian', query: 'Red Sauce, Paris' },
                { name: 'SAINTO', note: 'Hamburger', query: 'SAINTO, Paris' },
                { name: 'Boulangerie du Sentier', note: 'Bakery', query: 'Boulangerie du Sentier, Paris' },
                { name: 'Le Bon Georges', note: 'French', query: 'Le Bon Georges, Paris' },
                { name: 'SHWI Canal', note: 'Lebanese', query: 'SHWI Canal, Paris' },
                { name: 'Rôtisserie Segar', note: 'Chicken shop', query: 'Rôtisserie Segar, Paris' },
                { name: 'La Panifacture', note: 'Bakery', query: 'La Panifacture, Paris' },
                { name: 'Le Cheval d\'Or', note: 'Restaurant', query: 'Le Cheval d\'Or, Paris' },
                { name: 'Urfa Durum', note: 'Kebab shop', query: 'Urfa Durum, Paris' },
                { name: 'Rives', note: 'Restaurant', query: 'Rives, Paris' },
                { name: 'Our House', note: 'Japanese', query: 'Our House, Paris' },
                { name: 'BUDDY BUDDY · Nut Butter Coffee Bar', note: 'Coffee shop', query: 'BUDDY BUDDY · Nut Butter Coffee Bar, Paris' },
                { name: 'Du Pain et des Idées', note: 'Bakery', query: 'Du Pain et des Idées, Paris' },
                { name: 'Mamiche', note: 'Bakery', query: 'Mamiche, Paris' },
                { name: 'Bistrot Paul Bert', note: 'Bistro', query: 'Bistrot Paul Bert, Paris' },
                { name: 'La Bourse et La Vie', note: 'Bistro', query: 'La Bourse et La Vie, Paris' },
                { name: 'Frenchie Bar à Vins', note: 'French', query: 'Frenchie Bar à Vins, Paris' },
                { name: 'Dumbo', note: 'American', query: 'Dumbo, Paris' },
                { name: 'Chez Aline', note: 'Sandwich', query: 'Chez Aline, Paris' },
                { name: 'VINOBOBO', note: 'Wine bar', query: 'VINOBOBO, Paris' },
                { name: 'La Bonbonnette Bar a Vin', note: 'Wine bar', query: 'La Bonbonnette Bar a Vin, Paris' },
                { name: 'UVA Cave', note: 'Wine bar', query: 'UVA Cave, Paris' },
                { name: 'Caractère de Cochon', note: 'Cold cut store', query: 'Caractère de Cochon, Paris' },
                { name: 'Le Petit Vendôme', note: 'French', query: 'Le Petit Vendôme, Paris' },
                { name: 'Boot Café', note: 'Coffee shop', query: 'Boot Café, Paris' },
                { name: 'Terres de Café', note: 'Cafe', query: 'Terres de Café, Paris' },
                { name: 'Motors Coffee', note: 'Coffee shop', query: 'Motors Coffee, Paris' },
              ],
            },
            {
              type: 'map',
              id: 'ottawa',
              title: 'Ottawa',
              icon: 'ottawa',
              area: 'Ottawa, Canada',
              url: 'https://maps.app.goo.gl/8gbjL7EzYnGonZGz7',
              note: 'My Ottawa list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Sisters Mart', note: 'Health food store', query: 'Sisters Mart, Ottawa' },
                { name: 'DreamLand Cafe', note: 'Italian', query: 'DreamLand Cafe, Ottawa' },
                { name: 'Paninaro (Chinatown)', note: 'Sandwich', query: 'Paninaro (Chinatown), Ottawa' },
                { name: 'Le Poisson Bleu', note: 'Seafood', query: 'Le Poisson Bleu, Ottawa' },
                { name: 'Paper Tiger Noodle Bar', note: 'Fusion restaurant', query: 'Paper Tiger Noodle Bar, Ottawa' },
                { name: '107 Fourth Avenue Wine Bar & Café', note: 'Wine bar', query: '107 Fourth Avenue Wine Bar & Café, Ottawa' },
                { name: 'Flora Hall Brewing', note: 'Brewery', query: 'Flora Hall Brewing, Ottawa' },
                { name: 'Spark Beer & Pizza', note: 'Brewpub', query: 'Spark Beer & Pizza, Ottawa' },
                { name: 'Buvette Daphnée', note: 'Restaurant', query: 'Buvette Daphnée, Ottawa' },
                { name: 'WARD 14', note: 'Bar', query: 'WARD 14, Ottawa' },
                { name: 'The Moonroom', note: 'Lounge bar', query: 'The Moonroom, Ottawa' },
                { name: 'Oat Couture Cafe', note: 'Cafe', query: 'Oat Couture Cafe, Ottawa' },
                { name: 'Bar Lupulus', note: 'Restaurant', query: 'Bar Lupulus, Ottawa' },
                { name: 'Retro Gusto', note: 'Restaurant', query: 'Retro Gusto, Ottawa' },
                { name: 'Aladdin Bakery', note: 'Bakery', query: 'Aladdin Bakery, Ottawa' },
                { name: 'Perch Restaurant', note: 'Restaurant', query: 'Perch Restaurant, Ottawa' },
                { name: 'Smash Daddy - Little Italy', note: 'Hamburger', query: 'Smash Daddy - Little Italy, Ottawa' },
                { name: 'Ceylonta', note: 'Sri Lankan', query: 'Ceylonta, Ottawa' },
                { name: 'Datsun', note: 'Asian', query: 'Datsun, Ottawa' },
                { name: 'Giulia', note: 'Italian', query: 'Giulia, Ottawa' },
                { name: 'Toasty Arepas', note: 'Restaurant', query: 'Toasty Arepas, Ottawa' },
                { name: 'Muckleston & Brockwell - A Fine Butchery', note: 'Butcher shop', query: 'Muckleston & Brockwell - A Fine Butchery, Ottawa' },
                { name: 'Nan\'s Parlour', note: 'Cocktail bar', query: 'Nan\'s Parlour, Ottawa' },
                { name: 'Riviera Ottawa', note: 'Restaurant', query: 'Riviera Ottawa, Ottawa' },
                { name: 'Little Victories Coffee Roasters - Glebe', note: 'Coffee shop', query: 'Little Victories Coffee Roasters - Glebe, Ottawa' },
                { name: 'Run2Patty', note: 'Restaurant', query: 'Run2Patty, Ottawa' },
                { name: 'Supply and Demand', note: 'Restaurant', query: 'Supply and Demand, Ottawa' },
                { name: 'Art-Is-In Bakery', note: 'Bakery', query: 'Art-Is-In Bakery, Ottawa' },
                { name: 'Heartbreakers Pizza - Parkdale Ave', note: 'Restaurant', query: 'Heartbreakers Pizza - Parkdale Ave, Ottawa' },
                { name: 'Bread By Us', note: 'Bakery', query: 'Bread By Us, Ottawa' },
                { name: 'Yakko Takko', note: 'Mexican', query: 'Yakko Takko, Ottawa' },
                { name: 'Tooth and Nail Brewing Company', note: 'Brewpub', query: 'Tooth and Nail Brewing Company, Ottawa' },
                { name: 'Torta Boyz', note: 'Mexican', query: 'Torta Boyz, Ottawa' },
                { name: 'True Loaf Bread Company', note: 'temporarily closed', query: 'True Loaf Bread Company, Ottawa' },
                { name: 'Wolf Down', note: 'Restaurant', query: 'Wolf Down, Ottawa' },
                { name: 'Subito Sandwich', note: 'Italian', query: 'Subito Sandwich, Ottawa' },
                { name: 'Gongfu Cafe & Bao', note: 'Restaurant', query: 'Gongfu Cafe & Bao, Ottawa' },
                { name: 'Burgers n\' Fries Forever', note: 'Restaurant', query: 'Burgers n\' Fries Forever, Ottawa' },
                { name: 'La Fiesta Latina', note: 'Mexican', query: 'La Fiesta Latina, Ottawa' },
                { name: 'Co Cham', note: 'Vietnamese', query: 'Co Cham, Ottawa' },
                { name: 'Table SODAM', note: 'Korean', query: 'Table SODAM, Ottawa' },
                { name: 'The Foxhole', note: 'Barber shop', query: 'The Foxhole, Ottawa' },
              ],
            },
            {
              type: 'map',
              id: 'stockholm',
              title: 'Stockholm',
              icon: 'stockholm',
              area: 'Stockholm, Sweden',
              url: 'https://maps.app.goo.gl/nhUxxqgACAqHfFJeA',
              note: 'My Stockholm list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'The Qave', note: 'West African', query: 'The Qave, Stockholm' },
                { name: 'Günters', note: 'Hot Dog', query: 'Günters, Stockholm' },
                { name: 'Frost Bageri', note: 'Bakery', query: 'Frost Bageri, Stockholm' },
                { name: 'Savant Bar', note: 'Wine bar', query: 'Savant Bar, Stockholm' },
                { name: 'ima street', note: 'Takeout Restaurant', query: 'ima street, Stockholm' },
                { name: 'ok ok', note: 'Restaurant', query: 'ok ok, Stockholm' },
                { name: 'TEDDYS', note: 'Restaurant', query: 'TEDDYS, Stockholm' },
                { name: 'BAR NINJA', note: 'Wine bar', query: 'BAR NINJA, Stockholm' },
                { name: 'Rollin\' Burgers', note: 'Restaurant', query: 'Rollin\' Burgers, Stockholm' },
                { name: 'Efendi Västberga - Kolgrill och kebab', note: 'Restaurant', query: 'Efendi Västberga - Kolgrill och kebab, Stockholm' },
                { name: 'Solkant Café & Roastery', note: 'Cafe', query: 'Solkant Café & Roastery, Stockholm' },
                { name: 'LYKKE NYTORGET', note: 'Cafeteria', query: 'LYKKE NYTORGET, Stockholm' },
                { name: 'Sandhäxan', note: 'Sandwich', query: 'Sandhäxan, Stockholm' },
                { name: 'Babette', note: 'Restaurant', query: 'Babette, Stockholm' },
                { name: 'Omnipollos hatt', note: 'Bar', query: 'Omnipollos hatt, Stockholm' },
                { name: 'Schmaltz Bar & Delicatessen', note: 'Restaurant', query: 'Schmaltz Bar & Delicatessen, Stockholm' },
                { name: 'Krümel Cookies & Crumbs', note: 'Bakery', query: 'Krümel Cookies & Crumbs, Stockholm' },
                { name: 'Lillebrors bageri', note: 'Bakery', query: 'Lillebrors bageri, Stockholm' },
                { name: '800 Grader Slice Shop', note: 'Pizza', query: '800 Grader Slice Shop, Stockholm' },
                { name: 'Tjoget', note: 'Restaurant', query: 'Tjoget, Stockholm' },
                { name: 'Blå dörren', note: 'Restaurant', query: 'Blå dörren, Stockholm' },
                { name: 'Stigberget’s Foot', note: 'Bar', query: 'Stigberget’s Foot, Stockholm' },
                { name: 'Tennstopet Restaurang - Bar & Pub', note: 'Restaurant', query: 'Tennstopet Restaurang - Bar & Pub, Stockholm' },
              ],
            },
            {
              type: 'map',
              id: 'london',
              title: 'London',
              icon: 'london',
              area: 'London, UK',
              url: 'https://maps.app.goo.gl/GHLa4hmy3TR36Ssn8',
              note: 'My London list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Dopi', note: 'Korean', query: 'Dopi, London' },
                { name: 'Roll Boys.', note: 'Bakery', query: 'Roll Boys., London' },
                { name: 'TOAD Bakery', note: 'Bakery', query: 'TOAD Bakery, London' },
                { name: 'Nostos Coffee', note: 'Coffee shop', query: 'Nostos Coffee, London' },
                { name: 'Prufrock Coffee', note: 'Coffee shop', query: 'Prufrock Coffee, London' },
                { name: 'Omotesando Koffee', note: 'Coffee shop', query: 'Omotesando Koffee, London' },
                { name: 'Redemption Roasters Piccadilly Circus', note: 'Coffee shop', query: 'Redemption Roasters Piccadilly Circus, London' },
                { name: 'Archetype Coffee', note: 'Coffee shop', query: 'Archetype Coffee, London' },
                { name: 'Rosslyn Coffee Queen Victoria Street', note: 'Coffee shop', query: 'Rosslyn Coffee Queen Victoria Street, London' },
                { name: 'WatchHouse Hanover', note: 'Coffee shop', query: 'WatchHouse Hanover, London' },
                { name: 'Special Guests Coffee', note: 'Coffee shop', query: 'Special Guests Coffee, London' },
                { name: 'Ottolenghi Marylebone', note: 'Deli', query: 'Ottolenghi Marylebone, London' },
                { name: 'HIDE', note: 'Modern European', query: 'HIDE, London' },
                { name: 'Fallow', note: 'Modern British', query: 'Fallow, London' },
                { name: 'E Pellicci', note: 'Italian', query: 'E Pellicci, London' },
                { name: 'Koya Soho', note: 'Japanese', query: 'Koya Soho, London' },
                { name: 'Granger & Co. King\'s Cross', note: 'Australian', query: 'Granger & Co. King\'s Cross, London' },
                { name: 'MiMi Mei Fair', note: 'Chinese', query: 'MiMi Mei Fair, London' },
                { name: 'Blacklock Covent Garden', note: 'Steak', query: 'Blacklock Covent Garden, London' },
                { name: 'ROVI by Ottolenghi', note: 'Mediterranean', query: 'ROVI by Ottolenghi, London' },
                { name: 'Little Mercies', note: 'Cocktail bar', query: 'Little Mercies, London' },
                { name: 'Sabor', note: 'Spanish', query: 'Sabor, London' },
                { name: 'Ronnie Scott\'s', note: 'Jazz', query: 'Ronnie Scott\'s, London' },
                { name: 'Quo Vadis', note: 'Modern European', query: 'Quo Vadis, London' },
                { name: 'Canton Blue', note: 'Cantonese', query: 'Canton Blue, London' },
                { name: 'SOMA Soho', note: 'Bar', query: 'SOMA Soho, London' },
                { name: 'Donia', note: 'Restaurant', query: 'Donia, London' },
                { name: 'The Connaught Bar', note: 'Cocktail bar', query: 'The Connaught Bar, London' },
                { name: 'Arcade Tottenham Court Road', note: 'Food court', query: 'Arcade Tottenham Court Road, London' },
                { name: 'Pophams', note: 'Bakery', query: 'Pophams, London' },
                { name: 'St. John', note: 'British', query: 'St. John, London' },
                { name: 'Bar Crispin', note: 'Restaurant', query: 'Bar Crispin, London' },
                { name: 'The Devonshire', note: 'Pub', query: 'The Devonshire, London' },
                { name: 'BLOODSPORTS by MEATliquor', note: 'Bar', query: 'BLOODSPORTS by MEATliquor, London' },
                { name: 'Canal Restaurant', note: 'Modern European', query: 'Canal Restaurant, London' },
                { name: 'Wine Bar Mayfair', note: 'Wine bar', query: 'Wine Bar Mayfair, London' },
                { name: 'Regency Cafe', note: 'Cafe', query: 'Regency Cafe, London' },
                { name: 'BiBi', note: 'Modern Indian restaurant', query: 'BiBi, London' },
                { name: 'Brigadiers', note: 'Indian', query: 'Brigadiers, London' },
                { name: 'DUCKSOUP', note: 'Eclectic', query: 'DUCKSOUP, London' },
                { name: 'Berenjak Soho', note: 'Persian', query: 'Berenjak Soho, London' },
                { name: 'Rochelle Canteen', note: 'Modern European', query: 'Rochelle Canteen, London' },
              ],
            },
            {
              type: 'map',
              id: 'montreal',
              title: 'Montreal',
              icon: 'montreal',
              area: 'Montreal, Canada',
              url: 'https://maps.app.goo.gl/omkaYfxf7bBZhMuZ8',
              note: 'My Montreal list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'BAR - Big in Japan', note: 'Cocktail bar', query: 'BAR - Big in Japan, Montreal' },
                { name: 'Numéro', note: 'Bar', query: 'Numéro, Montreal' },
                { name: 'vinvinvin', note: 'Bar', query: 'vinvinvin, Montreal' },
                { name: 'Knuckles', note: 'Restaurant', query: 'Knuckles, Montreal' },
                { name: 'Denise', note: 'Restaurant', query: 'Denise, Montreal' },
                { name: 'Jun I', note: 'Sushi', query: 'Jun I, Montreal' },
                { name: 'Grille-Nature', note: 'Restaurant', query: 'Grille-Nature, Montreal' },
                { name: 'Leila', note: 'Restaurant', query: 'Leila, Montreal' },
                { name: 'Restaurant Parapluie', note: 'Restaurant', query: 'Restaurant Parapluie, Montreal' },
                { name: 'Le Violon', note: 'Restaurant', query: 'Le Violon, Montreal' },
                { name: 'Bar Luz', note: 'Mexican', query: 'Bar Luz, Montreal' },
                { name: 'Rôtisserie La Lune', note: 'Restaurant', query: 'Rôtisserie La Lune, Montreal' },
                { name: 'Dreamy', note: 'Cafe', query: 'Dreamy, Montreal' },
                { name: 'Pasta Pooks', note: 'Italian', query: 'Pasta Pooks, Montreal' },
                { name: 'Double’s', note: 'Bar', query: 'Double’s, Montreal' },
                { name: 'Pizza Bouquet', note: 'Pizza', query: 'Pizza Bouquet, Montreal' },
                { name: 'Salle Climatisée', note: 'Restaurant', query: 'Salle Climatisée, Montreal' },
                { name: 'Pizza Toni - Saint Viateur', note: 'Restaurant', query: 'Pizza Toni - Saint Viateur, Montreal' },
                { name: 'Falafel Yoni', note: 'Falafel', query: 'Falafel Yoni, Montreal' },
                { name: 'larrys', note: 'Restaurant', query: 'larrys, Montreal' },
                { name: 'Fairmount Bagel', note: 'Bagel shop', query: 'Fairmount Bagel, Montreal' },
                { name: 'Wilensky\'s Light Lunch Inc', note: 'Sandwich', query: 'Wilensky\'s Light Lunch Inc, Montreal' },
                { name: 'Le Bar Darling', note: 'Bar', query: 'Le Bar Darling, Montreal' },
                { name: 'Ma Poule Mouillée', note: 'Portuguese', query: 'Ma Poule Mouillée, Montreal' },
                { name: 'Atwater Cocktail Club', note: 'Bar', query: 'Atwater Cocktail Club, Montreal' },
                { name: 'Garage Beirut', note: 'Lebanese', query: 'Garage Beirut, Montreal' },
                { name: 'Restaurant Beba', note: 'Restaurant', query: 'Restaurant Beba, Montreal' },
                { name: 'McKiernan Rôtisserie', note: 'Restaurant', query: 'McKiernan Rôtisserie, Montreal' },
                { name: 'Gia Vin & Grill', note: 'Italian', query: 'Gia Vin & Grill, Montreal' },
                { name: 'Restaurant Elena', note: 'Restaurant', query: 'Restaurant Elena, Montreal' },
                { name: 'Sumac', note: 'Middle Eastern', query: 'Sumac, Montreal' },
                { name: 'Miette Boulangerie', note: 'Bakery', query: 'Miette Boulangerie, Montreal' },
                { name: 'Le Vin Papillon', note: 'Restaurant', query: 'Le Vin Papillon, Montreal' },
                { name: 'Mignon Steak Frites', note: 'Restaurant', query: 'Mignon Steak Frites, Montreal' },
                { name: 'Stem Bar', note: 'Restaurant', query: 'Stem Bar, Montreal' },
                { name: 'September Cafe', note: 'Coffee shop', query: 'September Cafe, Montreal' },
                { name: 'Le Café Bloom', note: 'Cafe', query: 'Le Café Bloom, Montreal' },
                { name: 'Clarke Café (PSC)', note: 'Cafe', query: 'Clarke Café (PSC), Montreal' },
                { name: 'Milky Way Cocktail Bar', note: 'Bar', query: 'Milky Way Cocktail Bar, Montreal' },
                { name: 'Épicerie Pumpui', note: 'Thai', query: 'Épicerie Pumpui, Montreal' },
                { name: 'Vin Mon Lapin', note: 'Restaurant', query: 'Vin Mon Lapin, Montreal' },
                { name: 'Falafel St. Jacques', note: 'Middle Eastern', query: 'Falafel St. Jacques, Montreal' },
                { name: 'Pichai', note: 'Thai', query: 'Pichai, Montreal' },
                { name: 'Roch le Coq', note: 'Restaurant', query: 'Roch le Coq, Montreal' },
                { name: 'Damas', note: 'Syrian', query: 'Damas, Montreal' },
              ],
            },
            {
              type: 'map',
              id: 'boston',
              title: 'Boston',
              icon: 'boston',
              area: 'Boston, USA',
              url: 'https://maps.app.goo.gl/N8JV4Q4dgmjK33h66',
              note: 'My Boston list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Riccardo\'s Ristorante', note: 'Italian', query: 'Riccardo\'s Ristorante, Boston' },
                { name: 'Playa Bowls', note: 'Health Food', query: 'Playa Bowls, Boston' },
                { name: 'Myers+Chang', note: 'Chinese', query: 'Myers+Chang, Boston' },
                { name: 'sweetgreen - Healthy Salads, Wraps, and Bowls', note: 'Salad', query: 'sweetgreen - Healthy Salads, Wraps, and Bowls, Boston' },
                { name: 'Greystone Cafe, Bakery, and Provisions', note: 'Cafe', query: 'Greystone Cafe, Bakery, and Provisions, Boston' },
                { name: 'Mike & Patty\'s Bay Village', note: 'Breakfast', query: 'Mike & Patty\'s Bay Village, Boston' },
                { name: 'Charlie\'s Sandwich Shoppe', note: 'Diner', query: 'Charlie\'s Sandwich Shoppe, Boston' },
                { name: 'Cutty\'s', note: 'Sandwich', query: 'Cutty\'s, Boston' },
                { name: 'State Park', note: 'American', query: 'State Park, Boston' },
                { name: 'Yume Ga Arukara', note: 'Udon noodles', query: 'Yume Ga Arukara, Boston' },
                { name: 'Juliet', note: 'Bistro', query: 'Juliet, Boston' },
                { name: 'Gracenote Coffee Boston', note: 'Coffee shop', query: 'Gracenote Coffee Boston, Boston' },
                { name: 'Gene\'s Chinese Flatbread Cafe', note: 'Chinese', query: 'Gene\'s Chinese Flatbread Cafe, Boston' },
                { name: 'haley.henry', note: 'Wine bar', query: 'haley.henry, Boston' },
                { name: 'Sam LaGrassa\'s', note: 'Sandwich', query: 'Sam LaGrassa\'s, Boston' },
                { name: 'Barra', note: 'Restaurant', query: 'Barra, Boston' },
                { name: 'Giulia', note: 'Italian', query: 'Giulia, Boston' },
                { name: 'Yume Wo Katare', note: 'Ramen', query: 'Yume Wo Katare, Boston' },
                { name: 'Spoke Wine Bar', note: 'Wine bar', query: 'Spoke Wine Bar, Boston' },
                { name: 'Bagelsaurus', note: 'Bagel shop', query: 'Bagelsaurus, Boston' },
                { name: 'Toro', note: 'Spanish', query: 'Toro, Boston' },
                { name: 'Faccia a Faccia', note: 'Italian', query: 'Faccia a Faccia, Boston' },
              ],
            },
            {
              type: 'map',
              id: 'new-york',
              title: 'New York',
              icon: 'new-york',
              area: 'New York, USA',
              url: 'https://maps.app.goo.gl/s8GEftfm8sMUpAPh9',
              note: 'My New York list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Soso\'s', note: 'Restaurant', query: 'Soso\'s, New York' },
                { name: 'Win Son', note: 'Taiwanese', query: 'Win Son, New York' },
                { name: 'The Four Horsemen', note: 'New American', query: 'The Four Horsemen, New York' },
                { name: 'Rolo’s', note: 'Grill', query: 'Rolo’s, New York' },
                { name: 'Cervo\'s', note: 'Seafood', query: 'Cervo\'s, New York' },
                { name: 'Ceres', note: 'Pizza', query: 'Ceres, New York' },
                { name: 'ATOMIX', note: 'Korean', query: 'ATOMIX, New York' },
                { name: 'Sunn’s', note: 'Restaurant', query: 'Sunn’s, New York' },
                { name: 'Tolo', note: 'Chinese', query: 'Tolo, New York' },
                { name: 'Breeze', note: 'Sichuan', query: 'Breeze, New York' },
                { name: 'Sweetie\'s K-Chicken', note: 'Korean', query: 'Sweetie\'s K-Chicken, New York' },
                { name: 'Frankel\'s Delicatessen & Appetizing', note: 'Sandwich', query: 'Frankel\'s Delicatessen & Appetizing, New York' },
                { name: 'Bernie’s', note: 'American — Burger, mozzarella sticks, dirty martini', query: 'Bernie’s, New York' },
                { name: 'ACRE', note: 'Japanese', query: 'ACRE, New York' },
                { name: 'Lingo', note: 'Japanese', query: 'Lingo, New York' },
                { name: 'Verge', note: 'Sushi', query: 'Verge, New York' },
                { name: 'Xi\'an Famous Foods (Greenpoint)', note: 'Chinese', query: 'Xi\'an Famous Foods (Greenpoint), New York' },
                { name: 'Oxomoco', note: 'Mexican', query: 'Oxomoco, New York' },
                { name: 'Leroy’s', note: 'Cocktail bar', query: 'Leroy’s, New York' },
                { name: 'Oh Dumplings', note: 'Chinese', query: 'Oh Dumplings, New York' },
                { name: 'Bar Americano', note: 'Bar', query: 'Bar Americano, New York' },
                { name: 'Edy\'s Grocer', note: 'Grocery store', query: 'Edy\'s Grocer, New York' },
                { name: 'Taqueria Ramirez', note: 'Mexican', query: 'Taqueria Ramirez, New York' },
                { name: 'Wenwen', note: 'Taiwanese', query: 'Wenwen, New York' },
                { name: 'Radio Bakery', note: 'Bakery', query: 'Radio Bakery, New York' },
                { name: 'Thai Villa', note: 'Thai', query: 'Thai Villa, New York' },
                { name: 'Playa Bowls', note: 'Health Food', query: 'Playa Bowls, New York' },
                { name: 'Sala Thai', note: 'Thai', query: 'Sala Thai, New York' },
                { name: 'Popup Bagels', note: 'Bagel shop', query: 'Popup Bagels, New York' },
                { name: 'LOS TACOS No.1', note: 'Tacos', query: 'LOS TACOS No.1, New York' },
                { name: 'Atoboy', note: 'Korean', query: 'Atoboy, New York' },
                { name: 'Chrissy’s Pizza', note: 'Pizza', query: 'Chrissy’s Pizza, New York' },
                { name: 'John\'s of Bleecker Street', note: 'Pizza', query: 'John\'s of Bleecker Street, New York' },
                { name: 'ARIARI', note: 'Korean', query: 'ARIARI, New York' },
                { name: 'Mission Sandwich Social', note: 'Sandwich', query: 'Mission Sandwich Social, New York' },
                { name: 'Lucali', note: 'Pizza', query: 'Lucali, New York' },
                { name: 'Fedoroff\'s Roast Pork', note: 'Cheesesteaks', query: 'Fedoroff\'s Roast Pork, New York' },
                { name: 'Russ & Daughters', note: 'Bagel shop', query: 'Russ & Daughters, New York' },
                { name: 'Mei Lai Wah', note: 'Chinese', query: 'Mei Lai Wah, New York' },
                { name: 'Tonii\'s Fresh Rice Noodle', note: 'Chinese', query: 'Tonii\'s Fresh Rice Noodle, New York' },
                { name: 'JG Melon', note: 'Grill', query: 'JG Melon, New York' },
                { name: 'Thai Diner', note: 'Thai', query: 'Thai Diner, New York' },
                { name: 'Court Street Grocers', note: 'Sandwich', query: 'Court Street Grocers, New York' },
                { name: 'Prince Street Pizza', note: 'Pizza', query: 'Prince Street Pizza, New York' },
                { name: 'Joe\'s Pizza', note: 'Pizza', query: 'Joe\'s Pizza, New York' },
                { name: 'Laser Wolf Brooklyn', note: 'Israeli', query: 'Laser Wolf Brooklyn, New York' },
                { name: 'Win Son Bakery', note: 'Bakery', query: 'Win Son Bakery, New York' },
                { name: 'Chez Ma Tante', note: 'Bistro', query: 'Chez Ma Tante, New York' },
                { name: 'Buvette', note: 'French', query: 'Buvette, New York' },
                { name: '% Arabica New York Nolita', note: 'Coffee shop', query: '% Arabica New York Nolita, New York' },
                { name: 'Birch Coffee', note: 'Coffee shop', query: 'Birch Coffee, New York' },
                { name: 'Variety Coffee Roasters', note: 'Coffee shop', query: 'Variety Coffee Roasters, New York' },
                { name: 'Little Flower Cafe', note: 'Coffee shop', query: 'Little Flower Cafe, New York' },
                { name: 'Faicco’s Italian Specialties', note: 'Deli', query: 'Faicco’s Italian Specialties, New York' },
                { name: 'Santa Fe BK', note: 'Southwestern American', query: 'Santa Fe BK, New York' },
                { name: 'Super Burrito', note: 'Burritos', query: 'Super Burrito, New York' },
                { name: 'P.J. Clarke\'s Third Avenue', note: 'American', query: 'P.J. Clarke\'s Third Avenue, New York' },
                { name: 'Ceremonia Bakeshop', note: 'Bakery', query: 'Ceremonia Bakeshop, New York' },
                { name: 'Milu', note: 'Chinese', query: 'Milu, New York' },
                { name: 'Mama Yoshi Mini Mart', note: 'Restaurant', query: 'Mama Yoshi Mini Mart, New York' },
                { name: 'Lioni Italian Heroes', note: 'Sandwich', query: 'Lioni Italian Heroes, New York' },
                { name: 'Mamoun\'s Falafel', note: 'Mediterranean', query: 'Mamoun\'s Falafel, New York' },
                { name: 'Scarr\'s Pizza', note: 'Pizza', query: 'Scarr\'s Pizza, New York' },
                { name: 'Mezzrow', note: 'Jazz', query: 'Mezzrow, New York' },
                { name: 'La Lanterna di Vittorio', note: 'Italian', query: 'La Lanterna di Vittorio, New York' },
              ],
            },
            {
              type: 'map',
              id: 'los-angeles',
              title: 'Los Angeles',
              icon: 'los-angeles',
              area: 'Los Angeles, USA',
              url: 'https://maps.app.goo.gl/tMhUTeEZeRFnctoi9',
              note: 'My Los Angeles list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Bridgetown Roti', note: 'Caribbean', query: 'Bridgetown Roti, Los Angeles' },
                { name: 'Q\'s Billiard Club & Restaurant', note: 'Pool hall', query: 'Q\'s Billiard Club & Restaurant, Los Angeles' },
                { name: 'Tacos El Chino', note: 'Tacos', query: 'Tacos El Chino, Los Angeles' },
                { name: 'Marvin', note: 'French', query: 'Marvin, Los Angeles' },
                { name: 'Dan Tana\'s', note: 'Italian', query: 'Dan Tana\'s, Los Angeles' },
                { name: 'Dante Beverly Hills', note: 'Restaurant', query: 'Dante Beverly Hills, Los Angeles' },
                { name: 'Mother Wolf', note: 'Italian', query: 'Mother Wolf, Los Angeles' },
                { name: 'Eggslut', note: 'Breakfast', query: 'Eggslut, Los Angeles' },
                { name: 'Amigos Birria Tacos Venice', note: 'Tacos', query: 'Amigos Birria Tacos Venice, Los Angeles' },
                { name: 'Tacos Los Cholos', note: 'Tacos', query: 'Tacos Los Cholos, Los Angeles' },
                { name: 'Mamie - WeHo', note: 'Italian', query: 'Mamie - WeHo, Los Angeles' },
                { name: 'Tijuanazo East Los Angeles', note: 'Tacos', query: 'Tijuanazo East Los Angeles, Los Angeles' },
                { name: 'La Dolce Vita', note: 'Italian', query: 'La Dolce Vita, Los Angeles' },
                { name: 'El Coyote Mexican Restaurant', note: 'Mexican', query: 'El Coyote Mexican Restaurant, Los Angeles' },
                { name: 'Easy Street Burgers', note: 'Hamburger', query: 'Easy Street Burgers, Los Angeles' },
                { name: 'Pizzeria Bianco', note: 'Pizza', query: 'Pizzeria Bianco, Los Angeles' },
                { name: 'Calabama', note: 'Breakfast', query: 'Calabama, Los Angeles' },
                { name: 'Yala Coffee', note: 'Coffee shop', query: 'Yala Coffee, Los Angeles' },
                { name: 'Sam’s Place', note: 'Wine bar', query: 'Sam’s Place, Los Angeles' },
                { name: 'Rasarumah', note: 'Asian', query: 'Rasarumah, Los Angeles' },
                { name: 'Sobuneh', note: 'Restaurant', query: 'Sobuneh, Los Angeles' },
                { name: 'KOMAL', note: 'Mexican', query: 'KOMAL, Los Angeles' },
                { name: 'Gjusta', note: 'Bakery', query: 'Gjusta, Los Angeles' },
                { name: 'Gjelina', note: 'American', query: 'Gjelina, Los Angeles' },
                { name: 'Mizlala Sycamore', note: 'Mediterranean', query: 'Mizlala Sycamore, Los Angeles' },
                { name: 'Pho Saigon Pearl', note: 'Vietnamese', query: 'Pho Saigon Pearl, Los Angeles' },
                { name: 'Jon & Vinny\'s Fairfax', note: 'Italian', query: 'Jon & Vinny\'s Fairfax, Los Angeles' },
                { name: 'Woon - Filipinotown', note: 'Chinese', query: 'Woon - Filipinotown, Los Angeles' },
                { name: 'Broad Street Oyster Company', note: 'Seafood', query: 'Broad Street Oyster Company, Los Angeles' },
                { name: 'King Taco # 2', note: 'Mexican', query: 'King Taco # 2, Los Angeles' },
                { name: 'Sushi Fumi', note: 'Sushi', query: 'Sushi Fumi, Los Angeles' },
                { name: 'Bavel', note: 'Restaurant', query: 'Bavel, Los Angeles' },
                { name: 'Hayato', note: 'Japanese', query: 'Hayato, Los Angeles' },
                { name: 'Jyan Isaac Bread', note: 'Bakery', query: 'Jyan Isaac Bread, Los Angeles' },
                { name: 'Leo\'s Tacos Truck', note: 'Tacos', query: 'Leo\'s Tacos Truck, Los Angeles' },
                { name: 'Mae Malai Thai House of Noodles', note: 'Thai', query: 'Mae Malai Thai House of Noodles, Los Angeles' },
                { name: 'Liu\'s Cafe', note: 'Taiwanese', query: 'Liu\'s Cafe, Los Angeles' },
                { name: 'Budonoki', note: 'Restaurant', query: 'Budonoki, Los Angeles' },
                { name: 'Langer\'s Delicatessen-Restaurant', note: 'Deli', query: 'Langer\'s Delicatessen-Restaurant, Los Angeles' },
                { name: 'Stereoscope Coffee', note: 'Coffee shop', query: 'Stereoscope Coffee, Los Angeles' },
                { name: 'Quarter Sheets', note: 'Pizza', query: 'Quarter Sheets, Los Angeles' },
                { name: 'Amboy Quality Meats & Delicious Burgers', note: 'Hamburger', query: 'Amboy Quality Meats & Delicious Burgers, Los Angeles' },
                { name: 'Thien Huong Restaurant', note: 'Vietnamese', query: 'Thien Huong Restaurant, Los Angeles' },
                { name: 'Santa Cecilia Restaurant', note: 'Mexican', query: 'Santa Cecilia Restaurant, Los Angeles' },
                { name: 'Yang Chow Restaurant', note: 'Chinese', query: 'Yang Chow Restaurant, Los Angeles' },
                { name: 'Baroo', note: 'Korean', query: 'Baroo, Los Angeles' },
                { name: 'Ditroit Taqueria', note: 'Mexican', query: 'Ditroit Taqueria, Los Angeles' },
                { name: 'Kim Hoa Hue Restaurant, El Monte', note: 'Vietnamese', query: 'Kim Hoa Hue Restaurant, El Monte, Los Angeles' },
                { name: 'Tacos La Carreta', note: 'Mexican', query: 'Tacos La Carreta, Los Angeles' },
                { name: 'Potato Chips Deli Beverly Grove', note: 'Sandwich', query: 'Potato Chips Deli Beverly Grove, Los Angeles' },
                { name: 'Layla Bagels', note: 'Bagel shop', query: 'Layla Bagels, Los Angeles' },
              ],
            },
            {
              type: 'map',
              id: 'melbourne',
              title: 'Melbourne',
              icon: 'melbourne',
              area: 'Melbourne, Australia',
              url: 'https://maps.app.goo.gl/PoTeW4P6DGQfSUKh8',
              note: 'My Melbourne list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Attica', note: 'Fine dining', query: 'Attica, Melbourne' },
                { name: 'Mile End Bagels', note: 'Bagel shop', query: 'Mile End Bagels, Melbourne' },
                { name: 'Hector\'s Deli', note: 'Sandwich', query: 'Hector\'s Deli, Melbourne' },
                { name: 'Carlito\'s', note: 'Sandwich', query: 'Carlito\'s, Melbourne' },
                { name: 'Soi 38 Melbourne', note: 'Thai', query: 'Soi 38 Melbourne, Melbourne' },
                { name: 'ShanDong MaMa', note: 'Chinese', query: 'ShanDong MaMa, Melbourne' },
                { name: 'Hope St Radio', note: 'Wine bar', query: 'Hope St Radio, Melbourne' },
                { name: 'Geralds Bar', note: 'Bar', query: 'Geralds Bar, Melbourne' },
                { name: 'Very Good Falafel', note: 'Falafel', query: 'Very Good Falafel, Melbourne' },
                { name: 'A1 Bakery Fitzroy', note: 'Bakery', query: 'A1 Bakery Fitzroy, Melbourne' },
                { name: 'Abla\'s', note: 'Lebanese', query: 'Abla\'s, Melbourne' },
                { name: 'Trattoria Emilia', note: 'Italian', query: 'Trattoria Emilia, Melbourne' },
                { name: 'Kafeneion "emeis & emeis" Melbourne', note: 'Greek', query: 'Kafeneion "emeis & emeis" Melbourne, Melbourne' },
                { name: 'Lagoon Dining', note: 'Chinese', query: 'Lagoon Dining, Melbourne' },
                { name: 'Eat Pierogi Make Love', note: 'Polish', query: 'Eat Pierogi Make Love, Melbourne' },
                { name: 'Etta', note: 'Restaurant', query: 'Etta, Melbourne' },
                { name: 'Greasy Zoes', note: 'Australian', query: 'Greasy Zoes, Melbourne' },
                { name: 'Shop Ramen', note: 'Ramen', query: 'Shop Ramen, Melbourne' },
                { name: 'Bar Liberty', note: 'Wine bar', query: 'Bar Liberty, Melbourne' },
                { name: 'Stefanino Panino e Vino', note: 'Sandwich', query: 'Stefanino Panino e Vino, Melbourne' },
                { name: 'Sunrise Cafe', note: 'Vietnamese', query: 'Sunrise Cafe, Melbourne' },
                { name: 'Masses Bagels', note: 'Bagel shop', query: 'Masses Bagels, Melbourne' },
                { name: 'Toasted Truck and Deli - Moorabbin', note: 'Sandwich', query: 'Toasted Truck and Deli - Moorabbin, Melbourne' },
                { name: 'Nico\'s Sandwich Deli', note: 'Sandwich', query: 'Nico\'s Sandwich Deli, Melbourne' },
                { name: 'Supernormal', note: 'Asian fusion', query: 'Supernormal, Melbourne' },
              ],
            },
            {
              type: 'map',
              id: 'mexico-city',
              title: 'Mexico City',
              icon: 'mexico-city',
              area: 'Mexico City, Mexico',
              url: 'https://maps.app.goo.gl/5iSEwYVWrMht9uQg7',
              note: 'My Mexico City list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Puerto Roma', note: 'Seafood', query: 'Puerto Roma, Mexico City' },
                { name: 'El Vilsito', note: 'Tacos', query: 'El Vilsito, Mexico City' },
                { name: 'El Turix', note: 'Tacos', query: 'El Turix, Mexico City' },
                { name: 'Coox Hanal', note: 'Yucatán', query: 'Coox Hanal, Mexico City' },
                { name: 'Los Cocuyos', note: 'Tacos', query: 'Los Cocuyos, Mexico City' },
                { name: 'Tacos Ruben\'s', note: 'Tacos', query: 'Tacos Ruben\'s, Mexico City' },
                { name: 'Tacos El Huequito', note: 'Tacos', query: 'Tacos El Huequito, Mexico City' },
                { name: 'Los 3 Reyes', note: 'Mexican', query: 'Los 3 Reyes, Mexico City' },
                { name: 'Ticuchi', note: 'Grill', query: 'Ticuchi, Mexico City' },
                { name: 'Siembra Taquería', note: 'Tacos', query: 'Siembra Taquería, Mexico City' },
                { name: 'Páramo', note: 'Mexican', query: 'Páramo, Mexico City' },
                { name: 'La Casa de Toño en Zona Rosa', note: 'Mexican', query: 'La Casa de Toño en Zona Rosa, Mexico City' },
                { name: 'El Pialadero de Guadalajara', note: 'Restaurant', query: 'El Pialadero de Guadalajara, Mexico City' },
                { name: 'Blom Nápoles', note: 'Coffee shop', query: 'Blom Nápoles, Mexico City' },
                { name: 'Campobaja', note: 'Seafood', query: 'Campobaja, Mexico City' },
                { name: 'Pulso', note: 'Cafe', query: 'Pulso, Mexico City' },
                { name: 'Joe Gelato', note: 'Ice cream', query: 'Joe Gelato, Mexico City' },
                { name: 'Taquería Orinoco', note: 'Tacos', query: 'Taquería Orinoco, Mexico City' },
                { name: 'Eno', note: 'Mexican', query: 'Eno, Mexico City' },
                { name: 'Caldos de Gallina "Luis"', note: 'Mexican', query: 'Caldos de Gallina "Luis", Mexico City' },
                { name: 'Masala y Maíz', note: 'Restaurant', query: 'Masala y Maíz, Mexico City' },
                { name: 'Constela Café', note: 'Coffee shop', query: 'Constela Café, Mexico City' },
                { name: 'Tacos Los Alexis - Roma Norte', note: 'Tacos', query: 'Tacos Los Alexis - Roma Norte, Mexico City' },
                { name: 'Pollos Poncho', note: 'Chicken', query: 'Pollos Poncho, Mexico City' },
                { name: 'Licorería Limantour', note: 'Cocktail bar', query: 'Licorería Limantour, Mexico City' },
                { name: 'Cariñito Tacos', note: 'Tacos', query: 'Cariñito Tacos, Mexico City' },
                { name: 'Bósforo', note: 'Bar', query: 'Bósforo, Mexico City' },
                { name: 'Hugo', note: 'Wine bar', query: 'Hugo, Mexico City' },
                { name: 'Blanco Colima', note: 'Restaurant', query: 'Blanco Colima, Mexico City' },
                { name: 'Máximo', note: 'Fine dining', query: 'Máximo, Mexico City' },
                { name: 'Bulla Condesa', note: 'Restaurant', query: 'Bulla Condesa, Mexico City' },
                { name: 'Lardo', note: 'Mediterranean', query: 'Lardo, Mexico City' },
                { name: 'Casa Franca', note: 'Bar', query: 'Casa Franca, Mexico City' },
                { name: 'Taqueria "Los Amigos"', note: 'Tacos', query: 'Taqueria "Los Amigos", Mexico City' },
                { name: 'Tortas Catakil', note: 'Restaurant', query: 'Tortas Catakil, Mexico City' },
                { name: 'Jazzatlán Capital', note: 'Restaurant', query: 'Jazzatlán Capital, Mexico City' },
                { name: 'Tacos la soledad', note: 'Tacos', query: 'Tacos la soledad, Mexico City' },
                { name: 'Contramar', note: 'Seafood', query: 'Contramar, Mexico City' },
                { name: 'Lalo!', note: 'Italian', query: 'Lalo!, Mexico City' },
                { name: 'Mi Compa Chava Marisquería', note: 'Seafood', query: 'Mi Compa Chava Marisquería, Mexico City' },
                { name: 'La Pezciosa', note: 'Tacos', query: 'La Pezciosa, Mexico City' },
                { name: 'Tacos Joven - Tacos de Canasta a domicilio', note: 'Tacos', query: 'Tacos Joven - Tacos de Canasta a domicilio, Mexico City' },
              ],
            },
            {
              type: 'map',
              id: 'denver',
              title: 'Denver',
              icon: 'denver',
              area: 'Denver, USA',
              url: 'https://maps.app.goo.gl/9YXC42N3MNwC38219',
              note: 'My Denver list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'La Sabrosita', note: 'Mexican', query: 'La Sabrosita, Denver' },
                { name: 'Cart Driver Lo-Hi', note: 'Pizza', query: 'Cart Driver Lo-Hi, Denver' },
                { name: 'Tacos Joe', note: 'Tacos', query: 'Tacos Joe, Denver' },
                { name: 'PokeClub', note: 'Poke bar', query: 'PokeClub, Denver' },
                { name: 'Whole Nectar Smoothie Bar', note: 'Restaurant', query: 'Whole Nectar Smoothie Bar, Denver' },
                { name: 'Playa Bowls', note: 'Health food', query: 'Playa Bowls, Denver' },
                { name: 'Crema Coffee House', note: 'Coffee shop', query: 'Crema Coffee House, Denver' },
                { name: 'Little Owl Coffee', note: 'Coffee shop', query: 'Little Owl Coffee, Denver' },
                { name: 'Glo Noodle House', note: 'Restaurant', query: 'Glo Noodle House, Denver' },
                { name: 'Ash\'Kara', note: 'Mediterranean', query: 'Ash\'Kara, Denver' },
                { name: 'Smok Barbecue', note: 'Barbecue', query: 'Smok Barbecue, Denver' },
                { name: 'Mister Oso RiNo', note: 'Tacos', query: 'Mister Oso RiNo, Denver' },
                { name: 'Nana’s Dim Sum & Dumplings', note: 'Asian', query: 'Nana’s Dim Sum & Dumplings, Denver' },
                { name: 'El Taco De Mexico', note: 'Mexican', query: 'El Taco De Mexico, Denver' },
                { name: 'Sap Sua', note: 'Vietnamese', query: 'Sap Sua, Denver' },
                { name: 'Urban Burma', note: 'Burmese', query: 'Urban Burma, Denver' },
                { name: 'BRUTO', note: 'Restaurant', query: 'BRUTO, Denver' },
                { name: 'La Diabla Pozole y Mezcal', note: 'Mexican', query: 'La Diabla Pozole y Mezcal, Denver' },
                { name: 'Point Easy Denver', note: 'Restaurant', query: 'Point Easy Denver, Denver' },
                { name: 'Yuan Wonton', note: 'Asian', query: 'Yuan Wonton, Denver' },
                { name: 'Alma Fonda Fina', note: 'Restaurant', query: 'Alma Fonda Fina, Denver' },
                { name: 'major tom', note: 'Restaurant', query: 'major tom, Denver' },
                { name: 'Kawa Ni', note: 'Restaurant', query: 'Kawa Ni, Denver' },
                { name: 'Fish N Beer', note: 'Seafood', query: 'Fish N Beer, Denver' },
                { name: 'Hop Alley', note: 'Chinese', query: 'Hop Alley, Denver' },
                { name: 'Safta', note: 'Restaurant', query: 'Safta, Denver' },
                { name: 'Kiké’s Red Tacos', note: 'Mexican', query: 'Kiké’s Red Tacos, Denver' },
                { name: 'Odie B\'s Sunnyside', note: 'Restaurant', query: 'Odie B\'s Sunnyside, Denver' },
                { name: 'Hops & Pie', note: 'Pizza', query: 'Hops & Pie, Denver' },
                { name: 'Call Your Mother Deli - Tennyson', note: 'Bagel shop', query: 'Call Your Mother Deli - Tennyson, Denver' },
                { name: 'Hey Kiddo', note: 'Restaurant', query: 'Hey Kiddo, Denver' },
                { name: 'Tocabe, An American Indian Eatery', note: 'Native American', query: 'Tocabe, An American Indian Eatery, Denver' },
              ],
            },
            {
              type: 'map',
              id: 'copenhagen',
              title: 'Copenhagen',
              icon: 'copenhagen',
              area: 'Copenhagen, Denmark',
              url: 'https://maps.app.goo.gl/x7rJWAM5qZUfT5Vh9',
              note: 'My Copenhagen list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'ORSA', note: 'Cafe', query: 'ORSA, Copenhagen' },
                { name: 'OMAR', note: 'Restaurant', query: 'OMAR, Copenhagen' },
                { name: 'Pompette', note: 'Wine bar', query: 'Pompette, Copenhagen' },
                { name: 'Slurp Ramen Joint', note: 'Ramen', query: 'Slurp Ramen Joint, Copenhagen' },
                { name: 'Tour Østerbro', note: 'Hamburger', query: 'Tour Østerbro, Copenhagen' },
                { name: 'Bar MORO', note: 'Restaurant', query: 'Bar MORO, Copenhagen' },
                { name: 'Sinne gas bageri', note: 'Bakery', query: 'Sinne gas bageri, Copenhagen' },
                { name: 'Kontra Coffee', note: 'Coffee shop', query: 'Kontra Coffee, Copenhagen' },
                { name: 'Sommer Canteen', note: 'Cafe', query: 'Sommer Canteen, Copenhagen' },
                { name: 'Harry’s Place', note: 'Hot dog stand', query: 'Harry’s Place, Copenhagen' },
                { name: 'Restaurant Koan', note: 'Fine dining', query: 'Restaurant Koan, Copenhagen' },
                { name: 'Sushi Anaba', note: 'Sushi', query: 'Sushi Anaba, Copenhagen' },
                { name: 'Kiin Kiin', note: 'Fine dining', query: 'Kiin Kiin, Copenhagen' },
                { name: 'Den Vandrette', note: 'Wine bar', query: 'Den Vandrette, Copenhagen' },
                { name: 'Balderdash', note: 'Bar', query: 'Balderdash, Copenhagen' },
                { name: 'Slurp Ramen', note: 'Ramen', query: 'Slurp Ramen, Copenhagen' },
                { name: 'Propaganda', note: 'Korean', query: 'Propaganda, Copenhagen' },
                { name: 'Silberbauers Bistro', note: 'Bistro', query: 'Silberbauers Bistro, Copenhagen' },
                { name: 'SURT', note: 'Pizza', query: 'SURT, Copenhagen' },
                { name: 'GRØD Vesterbro', note: 'Porridge', query: 'GRØD Vesterbro, Copenhagen' },
                { name: 'Prolog Coffee Bar Meatpacking District', note: 'Coffee shop', query: 'Prolog Coffee Bar Meatpacking District, Copenhagen' },
                { name: 'Warpigs Brewpub', note: 'Brewpub', query: 'Warpigs Brewpub, Copenhagen' },
                { name: 'Høst', note: 'Fine dining', query: 'Høst, Copenhagen' },
                { name: 'BRUS', note: 'Brewpub', query: 'BRUS, Copenhagen' },
                { name: 'Aamanns Deli & Takeaway (Østerbro)', note: 'Takeaway', query: 'Aamanns Deli & Takeaway (Østerbro), Copenhagen' },
                { name: 'Reffen Brewery', note: 'Brewery', query: 'Reffen Brewery, Copenhagen' },
                { name: 'Maroc Maroc', note: 'Restaurant', query: 'Maroc Maroc, Copenhagen' },
                { name: 'Alchemist', note: 'Fine dining', query: 'Alchemist, Copenhagen' },
                { name: 'Skt. Peders Bageri', note: 'Bakery', query: 'Skt. Peders Bageri, Copenhagen' },
                { name: 'Vækst', note: 'Modern European', query: 'Vækst, Copenhagen' },
                { name: 'Punk Royale Copenhagen', note: 'Fine dining', query: 'Punk Royale Copenhagen, Copenhagen' },
                { name: 'Gasoline Grill', note: 'Hamburger', query: 'Gasoline Grill, Copenhagen' },
                { name: 'Selma', note: 'Danish', query: 'Selma, Copenhagen' },
                { name: 'Juno the bakery', note: 'Bakery', query: 'Juno the bakery, Copenhagen' },
                { name: 'Pauli', note: 'temporarily closed', query: 'Pauli, Copenhagen' },
                { name: 'Barr', note: 'Restaurant', query: 'Barr, Copenhagen' },
                { name: 'Restaurant JATAK', note: 'Fine dining', query: 'Restaurant JATAK, Copenhagen' },
                { name: 'Noma', note: 'Scandinavian', query: 'Noma, Copenhagen' },
              ],
            },
            {
              type: 'map',
              id: 'gothenburg',
              title: 'Gothenburg',
              icon: 'gothenburg',
              area: 'Gothenburg, Sweden',
              url: 'https://maps.app.goo.gl/Q1C3oJi5urYvM6xe6',
              note: 'My Gothenburg list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Bar Minimal', note: 'Restaurant', query: 'Bar Minimal, Gothenburg' },
                { name: 'Björns Bar', note: 'Wine bar — Reco from our super cool server', query: 'Björns Bar, Gothenburg' },
                { name: 'Stranger', note: 'Cocktail bar — Speakeasy, but everyone knows about it - knock knock', query: 'Stranger, Gothenburg' },
                { name: 'BLOKK - Restaurang & Cocktailbar', note: 'Restaurant', query: 'BLOKK - Restaurang & Cocktailbar, Gothenburg' },
                { name: 'Familjen', note: 'Swedish — Bib gourmand, beautiful wines from all over Europe.', query: 'Familjen, Gothenburg' },
                { name: 'Le 20ème', note: 'Wine bar', query: 'Le 20ème, Gothenburg' },
                { name: 'Mugwort\'s BBQ Shack', note: 'Southwestern American', query: 'Mugwort\'s BBQ Shack, Gothenburg' },
                { name: 'La Fonda Mexicana', note: 'Mexican', query: 'La Fonda Mexicana, Gothenburg' },
                { name: 'Wine Mechanics (Gamlestan)', note: 'Winery', query: 'Wine Mechanics (Gamlestan), Gothenburg' },
                { name: 'Spike Brewery', note: 'Brewery', query: 'Spike Brewery, Gothenburg' },
                { name: 'Rollin Bistros Backyard', note: 'Restaurant', query: 'Rollin Bistros Backyard, Gothenburg' },
                { name: 'Morgon Coffee Roasters', note: 'Coffee roastery', query: 'Morgon Coffee Roasters, Gothenburg' },
                { name: 'Bar Bruno', note: 'Cocktail bar', query: 'Bar Bruno, Gothenburg' },
                { name: 'Restaurang Carbon', note: 'Fine dining', query: 'Restaurang Carbon, Gothenburg' },
                { name: 'Human Restaurang', note: 'Fine dining', query: 'Human Restaurang, Gothenburg' },
                { name: 'Södra Larm Bar & Bistro', note: 'Restaurant', query: 'Södra Larm Bar & Bistro, Gothenburg' },
                { name: 'Brunchoteket', note: 'Brunch', query: 'Brunchoteket, Gothenburg' },
                { name: 'Restaurant Tizne', note: 'Fine dining', query: 'Restaurant Tizne, Gothenburg' },
                { name: 'Koka', note: 'Fine dining', query: 'Koka, Gothenburg' },
                { name: 'Grano GBG', note: 'Restaurant', query: 'Grano GBG, Gothenburg' },
                { name: 'Alvar & Ivar Surdegsbageri', note: 'Bakery', query: 'Alvar & Ivar Surdegsbageri, Gothenburg' },
                { name: 'Epoque - Restaurang och vinbar i Göteborg', note: 'Scandinavian', query: 'Epoque - Restaurang och vinbar i Göteborg, Gothenburg' },
                { name: 'Viktors Kaffe', note: 'Cafe', query: 'Viktors Kaffe, Gothenburg' },
                { name: 'Bar La Lune', note: 'Restaurant', query: 'Bar La Lune, Gothenburg' },
                { name: 'SK Mat & Människor', note: 'Swedish', query: 'SK Mat & Människor, Gothenburg' },
                { name: 'Dirty Records', note: 'Vegetarian', query: 'Dirty Records, Gothenburg' },
                { name: 'Poppy', note: 'Scandinavian', query: 'Poppy, Gothenburg' },
                { name: 'Sjöbaren Fisk & Skaldjur i Haga', note: 'Seafood', query: 'Sjöbaren Fisk & Skaldjur i Haga, Gothenburg' },
                { name: 'Vi Viet', note: 'Vietnamese', query: 'Vi Viet, Gothenburg' },
              ],
            },
            {
              type: 'map',
              id: 'nashville',
              title: 'Nashville',
              icon: 'nashville',
              area: 'Nashville, USA',
              url: 'https://maps.app.goo.gl/DDaVXEaaFbzdbsb97',
              note: 'My Nashville list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'Retrograde Coffee', note: 'Cafe', query: 'Retrograde Coffee, Nashville' },
                { name: 'Elegy Coffee Downtown', note: 'Coffee shop', query: 'Elegy Coffee Downtown, Nashville' },
                { name: 'L & L Market', note: 'Market', query: 'L & L Market, Nashville' },
                { name: 'Wild Berry Acai', note: 'Açaí shop', query: 'Wild Berry Acai, Nashville' },
                { name: 'Butcher & Bee', note: 'Mediterranean', query: 'Butcher & Bee, Nashville' },
                { name: 'All or Nothing Bagels NORTH', note: 'Bakery', query: 'All or Nothing Bagels NORTH, Nashville' },
                { name: 'Henrietta Red', note: 'Oyster bar', query: 'Henrietta Red, Nashville' },
                { name: 'Husk Nashville', note: 'Southern', query: 'Husk Nashville, Nashville' },
                { name: 'Biscuit Love', note: 'Breakfast', query: 'Biscuit Love, Nashville' },
                { name: 'Hattie B\'s Hot Chicken - Midtown', note: 'Chicken', query: 'Hattie B\'s Hot Chicken - Midtown, Nashville' },
                { name: 'Bolton\'s Spicy Chicken & Fish', note: 'Southern', query: 'Bolton\'s Spicy Chicken & Fish, Nashville' },
                { name: 'Dino\'s Bar & Grill', note: 'American', query: 'Dino\'s Bar & Grill, Nashville' },
                { name: 'Maíz De La Vida Food Truck', note: 'Tacos', query: 'Maíz De La Vida Food Truck, Nashville' },
                { name: 'Maíz De La Vida Fonda Fina', note: 'Mexican', query: 'Maíz De La Vida Fonda Fina, Nashville' },
                { name: 'Lyra', note: 'Middle Eastern', query: 'Lyra, Nashville' },
                { name: 'Big Al\'s Deli', note: 'Deli', query: 'Big Al\'s Deli, Nashville' },
                { name: 'East Side Banh Mi', note: 'Vietnamese', query: 'East Side Banh Mi, Nashville' },
                { name: 'Southern Grist - East Nashville', note: 'Bar', query: 'Southern Grist - East Nashville, Nashville' },
                { name: 'Kisser', note: 'Japanese', query: 'Kisser, Nashville' },
                { name: 'SS Gai', note: 'Thai', query: 'SS Gai, Nashville' },
                { name: 'Shotgun Willie\'s BBQ', note: 'Barbecue', query: 'Shotgun Willie\'s BBQ, Nashville' },
                { name: 'Rolf and Daughters', note: 'New American', query: 'Rolf and Daughters, Nashville' },
                { name: 'Xiao Bao', note: 'Asian', query: 'Xiao Bao, Nashville' },
                { name: 'Wilburn Street Tavern', note: 'Bar — Fun dive bar', query: 'Wilburn Street Tavern, Nashville' },
                { name: 'Folk', note: 'American', query: 'Folk, Nashville' },
                { name: 'Redheaded Stranger', note: 'Tex Mex', query: 'Redheaded Stranger, Nashville' },
              ],
            },
            {
              type: 'map',
              id: 'madrid',
              title: 'Madrid',
              icon: 'madrid',
              area: 'Madrid, Spain',
              url: 'https://maps.app.goo.gl/QHrpLoSPD6aU6yrs5',
              note: 'My Madrid list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'El Gordito - Cantina', note: 'Espresso bar', query: 'El Gordito - Cantina, Madrid' },
                { name: 'focacciamo', note: 'Restaurant', query: 'focacciamo, Madrid' },
                { name: 'Hermanos Vinagre', note: 'Bar', query: 'Hermanos Vinagre, Madrid' },
                { name: 'Del Diego Cocktail Bar', note: 'Cocktail bar', query: 'Del Diego Cocktail Bar, Madrid' },
                { name: 'Álex Cordobés (Velázquez)', note: 'Pie shop', query: 'Álex Cordobés (Velázquez), Madrid' },
                { name: 'CASA PEI+', note: 'Restaurant', query: 'CASA PEI+, Madrid' },
                { name: 'Room Mate Collection Alba', note: 'Hotel', query: 'Room Mate Collection Alba, Madrid' },
                { name: 'Casa Brava', note: 'Live music bar', query: 'Casa Brava, Madrid' },
                { name: 'Catalina Cafè', note: 'Cafe', query: 'Catalina Cafè, Madrid' },
                { name: 'Syra Coffee - Sol', note: 'Coffee shop', query: 'Syra Coffee - Sol, Madrid' },
                { name: 'Toma Café 1', note: 'Coffee shop', query: 'Toma Café 1, Madrid' },
                { name: 'StreetXO Madrid', note: 'Fusion restaurant', query: 'StreetXO Madrid, Madrid' },
                { name: 'Pez Tortilla', note: 'Tapas bar', query: 'Pez Tortilla, Madrid' },
                { name: 'Malacatín', note: 'Madrilian', query: 'Malacatín, Madrid' },
                { name: 'Restaurante Desde 1911', note: 'Fine dining', query: 'Restaurante Desde 1911, Madrid' },
                { name: 'Casa Toni', note: 'Tapas bar', query: 'Casa Toni, Madrid' },
                { name: 'Restaurant La Campana', note: 'Restaurant', query: 'Restaurant La Campana, Madrid' },
                { name: 'La Casa del Abuelo', note: 'Tapas bar', query: 'La Casa del Abuelo, Madrid' },
                { name: 'SALA DE DESPIECE 1 (SDD1)', note: 'Restaurant', query: 'SALA DE DESPIECE 1 (SDD1), Madrid' },
              ],
            },
            {
              type: 'map',
              id: 'lisbon',
              title: 'Lisbon',
              icon: 'lisbon',
              area: 'Lisbon, Portugal',
              url: 'https://maps.app.goo.gl/k1YCdzD5mVy5529q9',
              note: 'My Lisbon list. Click a spot to find it, or open the whole list in Google Maps.',
              places: [
                { name: 'LX Factory', note: 'Art center', query: 'LX Factory, Lisbon' },
                { name: 'Prado', note: 'Restaurant', query: 'Prado, Lisbon' },
                { name: 'Vino Vero', note: 'Wine bar', query: 'Vino Vero, Lisbon' },
                { name: 'Porto Santa Maria', note: 'Portuguese restaurant', query: 'Porto Santa Maria, Lisbon' },
                { name: 'Copenhagen Coffee Lab - Santos', note: 'Coffee shop', query: 'Copenhagen Coffee Lab - Santos, Lisbon' },
                { name: 'Time Out Market', note: 'Food court', query: 'Time Out Market, Lisbon' },
                { name: 'Simpli Coffee Avenida', note: 'Coffee', query: 'Simpli Coffee Avenida, Lisbon' },
                { name: 'Solar dos Nunes', note: 'Portuguese restaurant', query: 'Solar dos Nunes, Lisbon' },
                { name: 'COMOBÅ', note: 'Cafe', query: 'COMOBÅ, Lisbon' },
                { name: 'Dallas Burger Joint - São Bento', note: 'Burgers', query: 'Dallas Burger Joint - São Bento, Lisbon' },
                { name: 'Heim Cafe Santos', note: 'Brunch', query: 'Heim Cafe Santos, Lisbon' },
                { name: 'Acento Coffee', note: 'Coffee shop', query: 'Acento Coffee, Lisbon' },
                { name: 'Musa da Bica', note: 'Beer hall', query: 'Musa da Bica, Lisbon' },
                { name: 'Tricky\'s', note: 'Restaurant', query: 'Tricky\'s, Lisbon' },
                { name: 'Omakase Ri', note: 'Omakase — temporarily closed', query: 'Omakase Ri, Lisbon' },
                { name: 'The Folks Chiado', note: 'Specialty coffee', query: 'The Folks Chiado, Lisbon' },
                { name: 'Monkey Mash', note: 'Cocktail bar', query: 'Monkey Mash, Lisbon' },
                { name: 'Taberna Sal Grosso', note: 'Portuguese restaurant', query: 'Taberna Sal Grosso, Lisbon' },
                { name: 'Clube de Jornalistas', note: 'Restaurant', query: 'Clube de Jornalistas, Lisbon' },
                { name: 'Neighbourhood Cafe Lisbon', note: 'Cafe', query: 'Neighbourhood Cafe Lisbon, Lisbon' },
                { name: 'Tapisco', note: 'Tapas e petiscos', query: 'Tapisco, Lisbon' },
                { name: 'Páteo - Bairro do Avillez', note: 'Restaurant', query: 'Páteo - Bairro do Avillez, Lisbon' },
                { name: 'Bonjardim', note: 'Chicken', query: 'Bonjardim, Lisbon' },
                { name: 'Manteigaria', note: 'Pastries', query: 'Manteigaria, Lisbon' },
                { name: 'Maçã Verde', note: 'Portuguese', query: 'Maçã Verde, Lisbon' },
                { name: 'Tati', note: 'Restaurant', query: 'Tati, Lisbon' },
                { name: 'As Bifanas do Afonso', note: 'Portuguese — Awesome sandwich', query: 'As Bifanas do Afonso, Lisbon' },
                { name: 'Tasca Baldracca', note: 'Restaurant', query: 'Tasca Baldracca, Lisbon' },
                { name: 'Gambrinus', note: 'Portuguese — Bread is so good', query: 'Gambrinus, Lisbon' },
                { name: 'Solar dos Presuntos', note: 'Restaurant — Classic', query: 'Solar dos Presuntos, Lisbon' },
                { name: 'Isco Padaria', note: 'Bakery — Pastries and shit', query: 'Isco Padaria, Lisbon' },
                { name: 'Taberna da Rua das Flores', note: 'Bistro', query: 'Taberna da Rua das Flores, Lisbon' },
                { name: 'Red Frog', note: 'Cocktail bar', query: 'Red Frog, Lisbon' },
                { name: 'Lupita Pizzaria Cais do Sodré', note: 'Pizza', query: 'Lupita Pizzaria Cais do Sodré, Lisbon' },
                { name: 'Pastéis de Belém', note: 'Pastries', query: 'Pastéis de Belém, Lisbon' },
                { name: 'Boubou\'s', note: 'French', query: 'Boubou\'s, Lisbon' },
                { name: 'Cervejaria Ramiro', note: 'Seafood', query: 'Cervejaria Ramiro, Lisbon' },
                { name: 'O Velho Eurico', note: 'Restaurant', query: 'O Velho Eurico, Lisbon' },
                { name: 'Café de São Bento', note: 'Steak', query: 'Café de São Bento, Lisbon' },
                { name: 'A Valenciana', note: 'Restaurant', query: 'A Valenciana, Lisbon' },
                { name: 'Tasca da Esquina', note: 'Portuguese', query: 'Tasca da Esquina, Lisbon' },
                { name: 'Pigmeu', note: 'Restaurant', query: 'Pigmeu, Lisbon' },
                { name: 'Feitoria', note: 'Fine dining', query: 'Feitoria, Lisbon' },
              ],
            },
          ],
        },
        {
          type: 'recipe',
          id: 'bagels',
          title: 'Bagels',
          icon: 'bagel',
          serves: '~14 small bagels',
          time: '2 days (mostly waiting)',
          source: 'https://docs.google.com/document/d/1LTdMHqFdjTvnNiZU3QcrJegVDtM5eDW9W8UjopKyiaY/edit?usp=sharing',
          ingredients: [
            '350 g water, at 95°F',
            '650 g hard bread flour (250 g for the sponge, 400 g later)',
            '3 g active dry yeast',
            '25 g white sugar',
            '25 g diastatic malt powder (yes, buy this FFS)',
            '10 g Diamond Crystal kosher salt',
            'Boiling: water plus about 1 tbsp each honey and molasses',
            'Toppings: seeds, cheese, jalapeño. Everything mix = 1 tbsp poppy, 1 tbsp sesame, ¼ tsp caraway, flaky salt',
          ],
          steps: [
            'Day 1, 10:00 am. Sponge: mix all the water, all the yeast and 250 g flour. Cover and leave somewhere warm (oven off, light on) for 3 to 6 hours.',
            'Day 1, 4:00 pm. Whisk the salt, sugar and malt powder into the remaining 400 g flour, then slowly add it to the sponge. Knead by hand for 15+ minutes until smooth and springy and it passes the windowpane test. Put on golf cart classics and take shifts if you can. Rest somewhere warm 1 to 3 hours.',
            'Day 1, 6:15 pm. Once doubled, portion with a scale and scissors: 65 g small, 85 g medium, 105 g large. Shape into tight balls, space out on a parchment-lined sheet, cover, and rise 1 to 2 hours. Never leave dough uncovered.',
            'Day 1, 7:45 pm. Pinch a hole through the centre of each ball and spin it on your fingers. Make the hole bigger than you think. Cover and put in the fridge overnight. Crack a pint, you earned it.',
            'Day 2, 9:00 am. Oven to 450°F, racks in the lower half, with a pizza stone or an upside-down baking sheet heating inside.',
            'Day 2, 9:15 am. Bring a big pot of water to a heavy simmer and add about 1 tbsp each honey and molasses. No malt powder? Add a pinch of baking soda. Prep toppings while it heats.',
            'Day 2, 9:45 am. Boil bagels 1 minute per side, then onto a rack and top them. Slide onto parchment on the hot stone or sheet and bake 20 to 25 minutes, until deep caramelized brown and blistered.',
            "Cool on a rack. Best warm and toasted. Freeze whatever you don't eat day one (good luck).",
          ],
          note: 'Cheddar jalapeño is the fan favourite. Questions on shaping? Just call me.',
        },
        {
          type: 'recipe',
          id: 'pickled-onions',
          title: "Hank's Pickled Onions",
          icon: 'pickled-onions',
          time: '10 min, plus cooling',
          source: 'https://docs.google.com/document/d/1s3CkMTPfqKeWS4tgrHV-V7sEXLU0-_IVJBDraFGnV4Q/edit?usp=sharing',
          ingredients: [
            '1 red onion',
            '1 red chili',
            '1 tbsp kosher salt',
            '1 tbsp white sugar',
            '¾ cup white distilled vinegar',
            '½ cup water',
            'Optional: mustard seed, pink peppercorns, cilantro, more chilies',
          ],
          steps: [
            'Cut the top and root off the onion, halve it, and slice thin from pole to pole. Thinner is better. Slice the chili too.',
            'Pack the onions and chili into a glass jar (or a bowl first, whatever works).',
            'Put the salt, sugar, water and vinegar in a saucepan with any spices you like. Heat on medium-high, stirring, just until the sugar and salt dissolve, 1 to 2 minutes.',
            'Pour the hot brine over the onions and put the lid on.',
            'Cool on the counter about 30 minutes, then into the fridge.',
          ],
          note: 'They turn bright pink in the fridge and last a month or two. If it smells wrong, it probably is. Good on just about anything.',
        },
        {
          type: 'image',
          id: 'bistrot-des-tournelles',
          title: '📍 Bistrot des Tournelles',
          src: '/photos/bistrot-des-tournelles.jpg',
          thumb: '/photos/bistrot-des-tournelles-thumb.jpg',
          caption: 'Bistrot des Tournelles, Paris',
        },
        {
          type: 'recipe',
          id: 'lemon-pasta',
          title: 'Weeknight Lemon Pasta',
          serves: '2',
          time: '20 min',
          ingredients: [
            '200 g spaghetti',
            '1 lemon, zest and juice',
            '40 g butter',
            '50 g parmesan, finely grated',
            'Black pepper, lots',
            'Handful of basil or parsley',
          ],
          steps: [
            'Cook the pasta in well-salted water until just shy of al dente. Save a mug of the water.',
            'Melt the butter in a wide pan over low heat and add the lemon zest.',
            'Move the pasta into the pan with a splash of pasta water and toss hard.',
            'Off the heat, add the parmesan and lemon juice, tossing until glossy. Loosen with more water if needed.',
            'Finish with pepper and torn herbs. Eat right away.',
          ],
          note: 'Sample recipe. The trick is taking it off the heat before the cheese goes in.',
        },
        {
          type: 'recipe',
          id: 'smash-burger',
          title: 'Smash Burgers',
          serves: '4',
          time: '25 min',
          ingredients: [
            '500 g ground beef (80/20)',
            '4 potato buns',
            '4 slices American cheese',
            '1 onion, sliced paper thin',
            'Pickles, mustard, salt',
          ],
          steps: [
            'Roll the beef into 8 loose balls. Keep them cold.',
            'Get a cast iron pan ripping hot. Toast the buns and set aside.',
            'Put a ball down, top with onion, and smash it flat with a spatula. Salt it.',
            'After about 90 seconds, scrape it up in one go, flip, add cheese, stack a second patty on top.',
            'Build with pickles and mustard.',
          ],
          note: 'Sample recipe.',
        },
        {
          type: 'link',
          id: 'serious-eats',
          title: 'Serious Eats',
          url: 'https://www.seriouseats.com/',
          note: 'Sample link. Where I go when I want to know why a recipe works.',
        },
        {
          type: 'note',
          id: 'food-list',
          title: 'Places to try in Toronto',
          date: '2026-09-12',
          body: '- that ramen spot on Queen West\n- the Portuguese bakery near Dundas\n- somewhere for proper Sichuan\n\n(sample list)',
        },
      ],
    },
    {
      id: 'clothes',
      name: 'Clothes',
      blurb: 'Stuff I wear, stuff I want, and where I read about it.',
      items: [
        {
          type: 'note',
          id: 'fall-rotation',
          title: 'Fall rotation',
          date: '2026-09-20',
          body: 'Raw denim, grey crewneck, chore coat, beat-up runners.\nThe chore coat does most of the work.\n\n(sample note)',
        },
        {
          type: 'link',
          id: 'heddels',
          title: 'Heddels',
          url: 'https://www.heddels.com/',
          note: 'Sample link. Denim, boots and workwear rabbit hole.',
        },
        {
          type: 'list',
          id: 'wishlist',
          title: 'Wishlist',
          rows: [
            { name: 'Waxed jacket', detail: 'Something that gets better with age (sample)' },
            { name: 'Loafers', detail: 'Brown, not too shiny (sample)' },
            { name: 'Wool overshirt', detail: 'For the in-between weeks (sample)' },
          ],
        },
      ],
    },
    {
      id: 'thoughts',
      name: 'Thoughts',
      blurb: "Short notes. Some of them I'll disagree with next year.",
      items: [
        {
          type: 'note',
          id: 'why-this-site',
          title: 'Why this site',
          date: '2026-09-30',
          body: "I wanted somewhere to put things I like that isn't a feed.\nNo algorithm, no likes. Just folders.\n\n(sample note)",
        },
        {
          type: 'note',
          id: 'on-slow-weekends',
          title: 'On slow weekends',
          date: '2026-09-14',
          body: 'Best weekends have one plan and a lot of room around it.\n\n(sample note)',
        },
      ],
    },
    {
      id: 'books',
      name: 'Books',
      blurb: "What I'm reading and what I'd hand to a friend.",
      items: [
        {
          type: 'list',
          id: 'reading',
          title: 'Reading list',
          rows: [
            { name: 'Kitchen Confidential', detail: 'Anthony Bourdain. Reading now. (sample)' },
            { name: 'Salt, Fat, Acid, Heat', detail: 'Samin Nosrat. Changed how I cook. (sample)' },
            { name: 'The Old Man and the Sea', detail: 'Hemingway. Short, and it hits. (sample)' },
          ],
        },
        {
          type: 'note',
          id: 'underlined',
          title: 'Underlined',
          date: '2026-09-02',
          body: 'Sample: a line from whatever I’m reading goes here, with a sentence on why it stuck.',
        },
      ],
    },
    {
      id: 'sport',
      name: 'Sport',
      blurb: 'Teams, games and the occasional run.',
      items: [
        { type: 'link', id: 'raptors', title: 'Toronto Raptors', url: 'https://www.nba.com/raptors', note: 'Sample link.' },
        { type: 'link', id: 'jays', title: 'Toronto Blue Jays', url: 'https://www.mlb.com/bluejays', note: 'Sample link.' },
      ],
    },
    {
      id: 'running',
      name: 'Running',
      icon: 'runner',
      blurb: 'Kilometers, obviously.',
      items: [
        {
          type: 'note',
          id: 'marathon-block',
          title: 'Marathon block',
          date: '2026-09-28',
          body: 'Marathon — sub-3:30 — Oct 19\n\n[ training log, sub-3:30 push, Oct 19 ]\n\nMon  5.2 km  easy\nWed  8.0 km  waterfront\nSat 12.4 km  long and slow\n\n(sample log)',
        },
        {
          type: 'note',
          id: 'tourmalet',
          title: 'Col du Tourmalet',
          body: '[ the climb story ]',
        },
      ],
    },
    {
      id: 'projects',
      name: 'Projects',
      icon: 'tools',
      blurb: "Things I've built, mostly from zero.",
      items: [
        { type: 'note', id: 'ljud', title: 'Ljud', body: 'AI workout playlist generation. Built from zero, no coding background.' },
        { type: 'note', id: 'bad-form', title: 'Bad Form', body: 'Running & cycling accessories. Score for Cancer campaign.' },
        { type: 'note', id: 'eddie', title: 'Eddie', body: 'Slack-based sales training tool.' },
        { type: 'note', id: 'life-rpg', title: 'Life RPG', body: '[ optional — include or drop ]' },
      ],
    },
    {
      id: 'recycle',
      name: 'Recycle Bin',
      icon: 'trash',
      blurb: 'Hey, get outta here!',
      items: [
        {
          type: 'note',
          id: 'bad-take',
          title: 'pineapple on pizza is wrong.txt',
          date: '2019-06-01',
          body: 'I was young.\n\n(sample note)',
        },
      ],
    },
  ],
};

/*
 * ---------------------------------------------------------------------------
 * Copy from the previous (job-focused) version of the site.
 * Not shown on the desktop any more. Kept here so nothing is lost; the
 * useful bits (projects, running) have been copied into folders above.
 * ---------------------------------------------------------------------------
 */

export const nav = [
  { href: '/work', label: 'Work' },
  { href: '/eat', label: 'Eat' },
  { href: '/build', label: 'Build' },
  { href: '/life', label: 'Life' },
  { href: '/#contact', label: 'Contact' },
];

export const hero = {
  eyebrow: 'Toronto, ON — open to work',
  headlineLines: ['Sells things.', 'Builds things.', 'Runs long distances', 'for no good reason.'],
  sub: 'Founding AE. Looking for the next team worth betting on.',
  tag: 'Marathon — sub-3:30 — Oct 19',
  coords: ['43.65°N, 79.38°W', 'Est. 2026'],
};

export const work = {
  status: 'Open to work',
  metaGrid: [
    { label: 'Status', body: 'Open to work' },
    { label: 'Here for', body: 'Founding / early sales roles, ideally social good or European-standard companies' },
    { label: 'Occupation', body: 'Founding AE. Also: builder, endurance athlete' },
  ],
  roles: [
    {
      when: '2024 – 2026',
      company: 'Clover Labs / RedRover',
      title: 'Founding AE',
      description: null as string | null,
      placeholder: '[ one line on what you closed/built here ]',
    },
    {
      when: '2021 – 2024',
      company: 'Hive.co',
      title: 'Founding AE → Senior Sales Manager',
      description: null as string | null,
      placeholder: '[ one line on the progression ]',
    },
  ],
  whatsNextPlaceholder: "[ one line: what's next ]",
};

export const eat = {
  placeholder: '[ cooking for people — recipes, dinner party stories, whatever this ends up being ]',
};

export const build = {
  projects: [
    { name: 'Ljud', description: 'AI workout playlist generation. Built from zero, no coding background.' },
    { name: 'Bad Form', description: 'Running & cycling accessories. Score for Cancer campaign.' },
    { name: 'Eddie', description: 'Slack-based sales training tool.' },
    { name: 'Life RPG', description: null as string | null, placeholder: '[ optional — include or drop ]' },
  ],
};

export const life = {
  cards: [
    { label: 'Col du Tourmalet', placeholder: '[ the climb story ]' },
    { label: 'Marathon block', placeholder: '[ training log, sub-3:30 push, Oct 19 ]' },
    { label: 'Thoughts', placeholder: "[ travel notes, running club, whatever's on your mind ]" },
  ],
};

export const contact = {
  eyebrow: 'Get in touch',
  email: 'hello@robkilometers.ca',
};

export const footer = {
  copyright: '© 2026 Robkilometers',
};
