// City icons for the City Guides folder (plus a bike for Cycling), drawn as 16x16 letter grids (one letter per pixel,
// '.' is transparent). Colours come from `palette`. Each pixel is drawn 2x2 on the 32x32 icon grid.

export const palette: Record<string, string> = {
  K: '#1a1a1a',
  W: '#ffffff',
  w: '#d8d8d8',
  G: '#8a8a8a',
  g: '#5a5a6a',
  B: '#7a5230',
  b: '#c08850',
  R: '#c8201a',
  r: '#e87a7a',
  M: '#8a1410',
  Y: '#f2cf5b',
  y: '#c9a227',
  O: '#e9631a',
  N: '#1a3a9a',
  L: '#3a8ae8',
  l: '#9fd4ff',
  E: '#3a8a2a',
  e: '#7cc05a',
  D: '#1a6a3a',
  S: '#6a3a1a',
  P: '#7a6a9a',
  p: '#a89ac0',
  C: '#fff0c0',
  T: '#2a7a78',
  c: '#e0b070',
};

export const cityArt = {
  paris: `
.......K........
.......B........
......KBK.......
......BbB.......
......BbB.......
.....KBBBK......
.....BbKbB......
.....BBBBB......
....KBbbbBK.....
....BB.K.BB.....
...BBBBBBBBB....
...BB.....BB....
..BB.......BB...
..BB.......BB...
.BB.........BB..
KKK.........KKK.
`,
  ottawa: `
.......e........
.......E........
......eEe.......
.....eEEEe......
.....EEEEE......
.....wwwww......
.....wKWKw......
.....wWKWw......
.....wwwww......
.....wGwGw......
.....wwwww......
.....wGwGw......
....wwwwwww.....
...wwGwwwGww....
..wGwwwGwwwGw...
..GGGGGGGGGGG...
`,
  stockholm: `
................
..NNNNNNNNNNNN..
..NNNNNNNNNNNN..
..NNYNNYYNNYNN..
..NNYYNYYNYYNN..
..NNYYYYYYYYNN..
..NNYRYYRYYRNN..
..NNYYYYYYYYNN..
..NNyyyyyyyyNN..
..NNNNNNNNNNNN..
..NNNNNNNNNNNN..
...NNNNNNNNNN...
....NNNNNNNN....
.....NNNNNN.....
......NNNN......
................
`,
  london: `
.......K........
......KyK.......
......yyy.......
.....yyyyy......
.....ccccc......
.....cWWWc......
.....cWKWc......
.....cWWKc......
.....cWWWc......
.....ccccc......
.....cBcBc......
.....ccccc......
.....cBcBc......
.....ccccc......
.....cBcBc......
....ccccccc.....
`,
  montreal: `
................
................
.....KKKKKK.....
...KKbbWbbbKK...
..KbbbbbbWbbbK..
..KbWbbbbbbbbK..
.KbbbbKKKKbbWbK.
.KbbbK....KbbbK.
.KbWbK....KbbbK.
.KbbbbKKKKbbbbK.
..KbbbbbWbbbbK..
..KBbbbbbbbbBK..
...KKBBBBBBKK...
.....KKKKKK.....
................
................
`,
  boston: `
..RR........RR..
.R..R......R..R.
.RRRR......RRRR.
..RR........RR..
...R...RR...R...
....R.RRRR.R....
.....RRRRRR.....
....RRKRRKRR....
.....RRRRRR.....
.....RMRRMR.....
......RRRR......
.....RMRRMR.....
......RRRR......
......RMMR......
.....RR..RR.....
....RR....RR....
`,
  'new-york': `
.......K........
.......G........
.......G........
......GwG.......
......www.......
.....GwwwG......
.....wlwlw......
.....wwwww......
....GwlwlwG.....
....wwwwwww.....
....wlwlwlw.....
...GwwwwwwwG....
...wlwlwlwlw....
...wwwwwwwww....
..GwlwlwlwlwG...
..wwwwwwwwwww...
`,
  'los-angeles': `
..........YYY...
.........YYYYY..
..EEE.....YYY...
.EEEEEE.........
EE..EEEEEE......
E..EE.B.EEEE....
..E...B....E....
......B.........
......B.........
.......B........
.......B........
.......B........
.......B........
......BB........
.cccccccccccccc.
cccccccccccccccc
`,
  melbourne: `
................
.......K........
......K.K.......
.....K...K......
..DDDDDDDDDDDD..
.DyyyyyyyyyyyyD.
.DllDllDllDllDD.
.DllDllDllDllDD.
.DDDDDDDDDDDDDD.
.DyyyyyyyyyyyyD.
.DDDDDDDDDDDDDD.
.DDKKDDDDDDKKDD.
..KGGK....KGGK..
...KK......KK...
GGGGGGGGGGGGGGGG
................
`,
  'mexico-city': `
................
................
................
................
................
...e.R..E.e.R...
..eERerEeReERe..
..SSSSSSSSSSSS..
.YYYYYYYYYYYYYY.
YyYYYYYYYYYYYYyY
YyyYYYYYYYYYYyyY
.YyyyyyyyyyyyyY.
..YYyyyyyyyyYY..
....YYYYYYYY....
................
................
`,
  denver: `
................
................
................
..........W.....
.........WWW....
.........WWP....
....W...WWPPP...
...WWW.WPPPPPP..
..WWPPWPPPPPPPP.
..PPPPPPPPgPPPP.
.PPPPgPPPPPgPPPP
.PPgPPPPgPPPPgPP
EEEEEEEEEEEEEEEE
EeEEEeEEEEeEEEeE
EEEEEEEEEEEEEEEE
................
`,
  copenhagen: `
................
................
................
..K...K...K...K.
.KRK.KYK.KLK.KOK
.RRR.YYY.LLL.OOO
RRRRYYYYLLLLOOOO
RWRRYWYYLWLLOWOO
RRRRYYYYLLLLOOOO
RWRRYWYYLWLLOWOO
RRRRYYYYLLLLOOOO
RKRRYKYYLKLLOKOO
llllllllllllllll
lLllllLlllllLlll
llllLllllllLllll
................
`,
  gothenburg: `
.......R........
.......K........
......WKW.......
.....WWKWW......
....WWWKWWW.....
...WWWWKWWWW....
..WWWWWKWWWWW...
.......K........
..WWW..K..WW....
.BBBBBBBBBBBBBB.
..BbbbbbbbbbbB..
...BBBBBBBBBB...
llllllllllllllll
lLlllLlllLlllLll
llLlllLlllLlllLl
................
`,
  nashville: `
.............KK.
............KBK.
...........KBK..
..........KBK...
.........KBK....
........KBK.....
.....bbKBKb.....
....bbbbbbbb....
...bbbbKKbbbb...
...bbbKKKKbbb...
...bbbbKKbbbb...
....bbbbbbbb....
...bbbbbbbbbb...
..bbbbBBBBbbbb..
..bbbbbbbbbbbb..
....bbbbbbbb....
`,
  madrid: `
.....EEEEEE.....
...EERDEEEREE...
..EDEEEEREEDEE..
..EREEDEEEEREE..
...EEEEREEDEE...
....EEEEEEEE....
.......SS.......
.BB....SS.......
BBBB...SS.......
BKBBB..SS.......
.BBBBBBSS.......
..BBBB.SS.......
..BBBB.SS.......
..BB.B.SS.......
..BB.B.SS.......
.eeeeeeeeeeeeee.
`,
  lisbon: `
................
................
................
................
....KKKKKKKK....
...KYYOYYYOYK...
..KYOYYYYYOYYK..
..KYYYYOYYYYYK..
..KYYOYYYYYOYK..
..KbbbbbbbbbbK..
...KbBbBbBbBK...
....KbbbbbbK....
.....KKKKKK.....
................
................
................
`,
  toronto: `
.......K........
.......G........
.......G........
.......w........
......GwG.......
.....wwwww......
.....KlKlK......
......www.......
.......w........
......wGw.......
......www.......
......wGw.......
.....wwwww......
.....wwGww......
....wwwwwww.....
EEEEEEEEEEEEEEEE
`,
  cycling: `
................
................
................
................
..........KK....
....KKK...K.....
.....RRRRRR.....
.....R...RR.....
..KKR.R..R.RKK..
.K..RKR.R.KR..K.
K..R..KRRK..R..K
K..RRRRR.K..R..K
K.....K.KK.....K
.K...K....K...K.
..KKK......KKK..
................
`,
};

export type CityIconName = keyof typeof cityArt;
